[tool.flet]
name = "fnaflauncher"
product = "FNAF Launcher"
description = "A cross-platform launcher for Five Nights at Freddy's"

[project]
name = "fnaflauncher"
version = "1.0.0"
description = "A cross-platform launcher for Five Nights at Freddy's"

[tool.flet.android]
package = "com.flet.fnaflauncher"
dependencies = [
  "pyjnius"
]

[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.REQUEST_INSTALL_PACKAGES" = true
"android.permission.QUERY_ALL_PACKAGES" = true